### ISSUE TITLE
R comment support

### ISSUE THREAD

**Issue by greenley** [preslavmihaylov/todocheck#1]
Submitting an issue per "If you don't see your favorite language in this table, but it does use one of the supported comment formats, submit an issue here" in the readme. Your scriptsMatcherFactory already supports the R language's comment syntax which is: # single-line only and multiple single-line "#" for multi-line behavior. The file extension for R language scripts is .R. The language does not require indentation for comments and does not require spaces between the "#" and the comment body, so it is valid in the context of singleLineTodoPattern's "^\\s*#.*TODO" requirement in todomatcher.go.

**Comment by preslavmihaylov** [comment]
Nice! Thanks for the succinct specification.

**Comment by preslavmihaylov** [comment]
Feel free to pull latest master & rebuild via `go build`.
