### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by regexident** [preslavmihaylov/todocheck#12]
This looks like a very cool tool! Congrats!

Would love to give it a ride with Rust.

> Comments in Rust code follow the general C++ style of line (//) and block (/* ... */) comment forms. Nested block comments are supported.
> 
> Non-doc comments are interpreted as a form of whitespace.

[Reference](https://doc.rust-lang.org/reference/comments.html)

The file extension of Rust source files is `.rs`.

**Comment by preslavmihaylov** [comment]
Thanks!

I'll need to extend the set of comment parsers for this one as nested multi-line comments aren't supported in todocheck yet.

**Comment by regexident** [comment]
For the sake of completeness: similar to Swift (https://github.com/preslavmihaylov/todocheck/issues/13#issuecomment-661720001) Rust also supports doc comments via `///`.

**Comment by regexident** [comment]
Piggybacking on @kiliankoe's [comment](https://github.com/preslavmihaylov/todocheck/issues/13#issuecomment-661720001) on Swift:

Rust also has a concept of documentation comments which begin with three slashes `///`, but that's more of editor concept (VSCode/IntelliJ render them differently) since they're already normal comments by starting with `//`. Just in case that makes a difference for the parser.
