### ISSUE TITLE
Run gofmt automatically on pull requests

### ISSUE THREAD

**Issue by preslavmihaylov** [preslavmihaylov/todocheck#138]
Extend the github actions to automatically run `gofmt` on every pull request to avoid styling issues resulting from people not having installed gofmt locally.

**Comment by sancroth** [comment]
Please do assign this to me @preslavmihaylov

**Comment by preslavmihaylov** [comment]
For now, we added a CI step which verifies that gofmt is ran locally to format all the necessary files

**Comment by preslavmihaylov** [comment]
It seems it's not as trivial to make gofmt format your code on pull request. For now, we'll suffice with just verifying the format
