### ISSUE TITLE
Groovy support

### ISSUE THREAD

**Issue by metteo** [preslavmihaylov/todocheck#14]
It would be helpful to scan Spock specifications or regular groovy projects.

**Comment by preslavmihaylov** [comment]
It seems groovy supports standard `//` & `/* */` comments. Support for it can be added easily

**Comment by metteo** [comment]
There are also groovydoc comments (`/** */`) which should be covered by `/* */` and [shebang lines](https://groovy-lang.org/syntax.html#_shebang_line).

One special thing about java / groovy comments is the usage of stars in the beginning of the comment line:
```
/*
 *
 *
 */
```
or
```
/**
 *
 *
 */
```
Can parser handle those?

**Comment by metteo** [comment]
Also please consider following script ([run!](https://groovyconsole.appspot.com/script/5159817136046080)):
```
//TODO: regular inline comment
/*
* block comment
*/
/**
* groovydoc comment
*/
 
def trippleDoubleQuotedString = """string start
    //TODO: inline comment inside a string block
 
    /* block comment inside a string block */
    /** groovydoc comment inside a string block */
string end"""
 
def trippleSingleQuotedString = '''string2 start
    //TODO: inline comment inside a string2 block
 
    /* block comment inside a string2 block */
    /** groovydoc comment inside a string2 block */
string2 end'''
 
println trippleDoubleQuotedString
println ''
println trippleSingleQuotedString
```
Which outputs:
```
string start
    //TODO: inline comment inside a string block

    /* block comment inside a string block */
    /** groovydoc comment inside a string block */
string end

string2 start
    //TODO: inline comment inside a string2 block

    /* block comment inside a string2 block */
    /** groovydoc comment inside a string2 block */
string2 end
```

**Comment by preslavmihaylov** [comment]
Thanks for taking the time to make that example, it is quite useful!

Just to make sure we're on the same page, the inline TODO comments inside multi-line strings shouldn't be matched by todocheck, right?

That is the behavior I'm intending to incorporate in all supported languages.

**Comment by metteo** [comment]
Yes, TODO comments are comments so if they are part of a string literal (regular or block) they shouldn't be interpreted as TODOs.

**Comment by metteo** [comment]
According to [this](https://mrhaki.blogspot.com/2011/10/groovy-goodness-default-groovy-script.html) (old) blog post groovy uses following file extensions:

- `groovy` (usual)
- `gsh` (groovy shell, scripts)
- `gvy` (rare)
- `gy` (rare)

**Comment by preslavmihaylov** [comment]
I've added support for groovy as part of #16 

I've added test for all the use-cases you mentioned + some more (see changed files under `testing/` directory).
