### ISSUE TITLE
Nim Support

### ISSUE THREAD

**Issue by bengsparks** [preslavmihaylov/todocheck#157]
Nim is one of the newer languages to gain traction, so perhaps it would be best to first discuss whether it should even be supported. 

Its single line comment syntax is identical to that of Python. However, its multiline syntax is `#[ ... ]#`, and is capable of being nested. As such, the implementation could probably be adapted from the preexisting matcher.

Supported file extensions are `.nim`, `.nims` and `.nimble`

```nim 
# An implementation of Hello World in Nim

when isMainModule: # this is more or less a compile time if
    echo "Hello World"
#[ 
Something very interesting about Nim is its decision to support Uniform Function Call Syntax.
You can inform yourself about this here: https://nim-lang.org/docs/manual.html#procedures
]#
```

**Comment by preslavmihaylov** [comment]
Hi Benjamin, the Nim language seems to be one which is not that popular, but the comment style it supports seems very similar to what we already have so I'm happy to support it if a contributor picks this up & submits a PR.
