### ISSUE TITLE
Add a go linter CI step

### ISSUE THREAD

**Issue by preslavmihaylov** [preslavmihaylov/todocheck#165]
The CI should run a go linter step to avoid fixing linter issues in pull requests.

Once its enabled, there would inevitably be linting issues throughout the codebase. Fix them as part of the pull request for adding the linter in CI.

**Comment by TheodosiouTh** [comment]
Is there anyone working on this issue. If not I would love to take a crack at it.

**Comment by preslavmihaylov** [comment]
@TheodosiouTh no one is looking at it at the moment. Feel free to take it on

**Comment by TheodosiouTh** [comment]
@preslavmihaylov  Could you assign me this issue, since I am working on it?
