### ISSUE TITLE
auth tokens cache overrides auth token specified via env variable

### ISSUE THREAD

**Issue by preslavmihaylov** [preslavmihaylov/todocheck#175]
Whenever you specify an auth token for e.g. domain `hello.myjira.net` with auth token via env variable:
```
$ TODOCHECK_AUTH_TOKEN=<auth-token> ./todocheck
```

if there is an auth token already present for that domain in `~/.todocheck/authtokens.yaml`, todocheck will use the auth token from that file vs. using the one specified via the env variable.

This shouldn't happen. The env variable should override the auth tokens cache.

**Comment by aaronangxz** [comment]
Hello! stumbled upon your repo and I'll love to start contributing to some minor issues :)

For this fix, can we make some changes to `acquireToken` in `authmanager.go`:
```go
	if store.Tokens[tokenKey] != "" {
		authCfg.Token = store.Tokens[tokenKey]
		return nil
	} else if envToken := os.Getenv(authTokenEnvVariable); envToken != "" {
		authCfg.Token = envToken
		return nil
	}
```

It seems like the cache token has higher priority than the env variable. CMIIW, thanks!

**Comment by preslavmihaylov** [comment]
hey, @aaronangxz thanks for considering contributing!

Go for it, feel free to open a PR!
