### ISSUE TITLE
Support machine friendly output format

### ISSUE THREAD

**Issue by abatilo** [preslavmihaylov/todocheck#3]
If we could have a JSON output format, or any other easy machine parseable format, I believe integrating this into something like vim's ALE plugin would be much easier.

**Comment by preslavmihaylov** [comment]
This is a good idea. I will consider it in a future release.

In the meantime, you could check out [this function](https://github.com/preslavmihaylov/todocheck/blob/master/testing/scenariobuilder/validations.go#L15) which parses the program's output. It's part of the custom testing framework I did for the project - based on verifying the binary's output.

**Comment by preslavmihaylov** [comment]
todocheck now supports output as json.

Usage:
```
todocheck --format json
```

Sample output:
```
[
   {
      "type":"Malformed todo",
      "filename":"tmp/main.groovy",
      "line":2,
      "message":"TODO should match pattern - TODO {task_id}:"
   },
   {
      "type":"Malformed todo",
      "filename":"tmp/main.groovy",
      "line":12,
      "message":"TODO should match pattern - TODO {task_id}:"
   },
   {
      "type":"Issue doesn't exist",
      "filename":"tmp/main.groovy",
      "line":15,
      "message":""
   }
]
```
