### ISSUE TITLE
Don't panic when someone has passed an unsupported issue tracker

### ISSUE THREAD

**Issue by preslavmihaylov** [preslavmihaylov/todocheck#44]
When someone specifies an unsupported issue tracker, a non-user friendly panic occurs. See #43 

Instead, validate the issue tracker & configuration beforehand & print a more user-friendly error message.

**Comment by mehdy** [comment]
I'm thinking of a `Validate()` method for the `Local` struct for this issue. We could call it right after creating a new local config and make sure we have the right config.
Let me know what you think.

**Comment by preslavmihaylov** [comment]
Yes, that sounds good. We can encapsulate all similar config validations there. Including #36

**Comment by mehdy** [comment]
> Yes, that sounds good. We can encapsulate all similar config validations there. Including #36

Exactly. So I'll be working on this.
