### ISSUE TITLE
Support for non-uppercase todo's

### ISSUE THREAD

**Issue by addiks** [preslavmihaylov/todocheck#48]
Currently the todochecker can only detect a todo if it is written all uppercase (like `# TODO: Lorem ipsum ...`). In some cases the todo may not br written in all uppercase but a different casing like all lowercase (which is sometimes common for annotations: `/** @todo: Lorem ipsum ... */` or camelcase: `# ToDo: Lorem ipsum ...`. These other casings are currently not detected by todocheck. This means that there are still quite a few todo's in our codebase that have gone unnoticed, and developers can still add todo's without writing an issue just by changing the casing. 

Would it be possible to change the detection logic so that the casing (uppercase / lowercase) are no longer relevant?

**Comment by preslavmihaylov** [comment]
I think that implementing this might harm some users as they might want to stick to the classic `TODO: <text>` format.

However, I think that it would be beneficial to allow users to specify a custom TODO format in addition to the classic one in `.todocheck.yaml` similar to how IntelliJ [provides the option](https://www.jetbrains.com/help/idea/using-todo.html) for one to configure his own todo patterns.

**Comment by addiks** [comment]
Mhh, I don't think that just changing the static format of the todo's is going to cut it for us. Annotations are generally not written all uppercase, but I don't want to just ban the otherwise extremely common `TODO` in all uppercase. Maybe it would be better to have a list of allowed formats (e.g.: `@todo` and `TODO`) configurable per project and detect all other formats (`ToDo`, `TOdO`) as malformed todo's?
I think that todocheck should at least detect differently formed todo's so that they do not go unnoticed. What it does with them afterwards is a different matter.
Would that be ok?

**Comment by preslavmihaylov** [comment]
Yes, that is what I meant. It would be beneficial to enable one to define his own custom valid todo formats per project.

I'll additionally create a task for detecting both lower & uppercase TODOs as invalid.

**Comment by TomekStaszkiewicz** [comment]
Hello @preslavmihaylov 

I would love to contribute to your project, are you ok with me taking this one?
As far as I understand I should handle two things in this task:
1. Parse proper config options
2. Change the way the regexp are generated

Of course + unit tests. :)

Am I right about it?

**Comment by preslavmihaylov** [comment]
Adding some clarification about how I think it's best to implement this by contributors:
 * Add a flag in the yaml file `matchCaseSensitive: true/false`
 * Extend existing classes to either support `TODO` like they currently do, but also enable supporting `todo/ToDo/etc`.
 * Document behavior in README

**Comment by preslavmihaylov** [comment]
@Emoto13 another good one you could pick up?

**Comment by Emoto13** [comment]
@preslavmihaylov Will start implementing it in the next few days probably 👍
