### ISSUE TITLE
Support shelling out to get issue information

### ISSUE THREAD

**Issue by Kirides** [preslavmihaylov/todocheck#5]
I propose a new "Issue tracker" which would be called `CLI`.  

The following would be equal to searching for an issue `1`
`./customIssueTrackerClient 1`
It it up to the commandline application to handle lookups and return the response it a way, the `todocheck` can consume it.

possible response format could be json:
```js
{
  "issue": "1",
  // one-of: STATE_OPEN (0), STATE_CLOSED (1), STATE_MISSING (-1), STATE_PULLREQUEST (2) 
  "state": -1,
  // [optional] Verbose message to be displayed to show more detailed information about the `state`
  "message": "Issue is closed"
}
```

**Comment by preslavmihaylov** [comment]
What is the use-case for this flow?

My idea was integrating todocheck with popular issue trackers out of the box (e.g. Jira, Github, Gitlab), so that users need not do anything on their end.

**Comment by Kirides** [comment]
we use a proprietary issue tracking system, which does not really offer any kind of real API. But you can instantiate it using COM, which makes it kinda automatable

**Comment by preslavmihaylov** [comment]
@Kirides As it currently stands, I don't see how this feature request can be implemented in `todocheck`. It sounds like a feature request for a new issue tracker, but the linter merely integrates with existing ones.

Instead, if you could describe some kind of a common protocol which would enable `todocheck` to integrate with custom issue trackers (e.g. via some socket IO?) we can discuss this again.
