### ISSUE TITLE
Return an error if github repository is not found or private

### ISSUE THREAD

**Issue by preslavmihaylov** [preslavmihaylov/todocheck#62]
Currently, if someone specifies a valid private github repository without an `apitoken`, `todocheck` won't report any error but will instead report all linked issues in TODOs as not found.

The reason is that Github returns status code `404 Not Found` instead of `403 Unauthorized` when querying private repositories for privacy/security reasons.

In this situation, it takes quite a while to find out what the issue is until you realize you haven't specified the `apitoken` in your configuration.

It would be helpful for `todocheck` to do the following request upon initializing the configuration:
```
curl https://api.github.com/repos/{user}/{repo}
```

If this request returns `200`, the repository exists. If it returns `404`, it might not exist OR is private.

Create a **on-initialize** hook for issuetrackers, which can do arbitrary checks. For github, this is the check to do.
If it doesn't pass AND there is no auth token specified, print the error message & exit:
```
Github repository %s not found. Are you accessing a private repository without a token?
```

**Comment by codykaup** [comment]
I'd love to snag this one to help out! Is it still up for grabs?

**Comment by preslavmihaylov** [comment]
Yeah, go ahead with!

**Comment by codykaup** [comment]
@preslavmihaylov any chance to get this one included in Hacktoberfest?

**Comment by preslavmihaylov** [comment]
Yeah, I just added the hacktoberfest topic to the repo. Let me know if there are any requirements than that to enlist the repo. Happy coding :)

**Comment by codykaup** [comment]
Oh you're the best. Thank you!

**Comment by preslavmihaylov** [comment]
Unfortunately, this issue is more convoluted than it first seems.

Here are the steps I see in hindsight to complete it:
 1. The `Validate` function has to be moved away from the `config` package into a separate package `validation`. The reason is that in order to make this validation, you would need access to the `issuetracker` package, which would create a cyclic dependency
 2. The `issuetracker` package needs to be extended with an additional function `HealthcheckURL` which returns the correct healthcheck URL for a given issue tracker. For github, that is `https://api.github.com/repos/{user}/{repo}`
 3. The `fetcher` package needs to be extended to support an additional function `isHealthy` which makes a request to the healthcheck URL and returns false if the status code is different from `200` or if any error occurs. It will also probably have to be renamed, but that can be left for another issue
 4. The `Validate` function has to use the `isHealthy` function to validate if the remote repository exists & return an error otherwise
