### ISSUE TITLE
Show a warning if no apitoken is specified for any github repository

### ISSUE THREAD

**Issue by preslavmihaylov** [preslavmihaylov/todocheck#63]
Github has a [rate limit in-place](https://developer.github.com/v3/#rate-limiting) for unauthenticated requests to their API which is 60 requests per hour.

For any production usage, this is a very low quota.
However, if the requests are authenticated (even if accessing public repositories), the quota is 5000 requests per hour, which should suffice for most use cases.

Therefore, a warning should be shown if the configuration lacks an `apitoken` for github repositories, regardless of whether the repository is private or not.

In scope of this issue is to include this warning in the README for public github repository setup as well.

You can reuse the mechanics of #62 for showing this warning.

**Comment by codykaup** [comment]
I'd like to snag this one as well if it's still available!

**Comment by preslavmihaylov** [comment]
@codykaup go ahead!
