### ISSUE TITLE
Just interesting

### ISSUE THREAD

**Issue by alifpay** [preslavmihaylov/todocheck#88]
Hi 
Just interesting, I read your blog about uber fx (https://pmihaylov.com/dependency-injection-go-fx/).

Why do not use uber fx in your repo?

**Comment by preslavmihaylov** [comment]
Hi Alif, thanks for checking out the blog post and being curious!

In that post, I mentioned that the framework is something which brings value in certain use cases but not all, especially if you're dealing with a small project.

todocheck is such a project. It's main function is around 60 LOC which is not too much so adding the framework would be an overhead. Especially given that this is an open source project, so I want to keep it digestible to first-time maintainers.
