### ISSUE TITLE
Add PHP support

### ISSUE THREAD

**Issue by atomicptr** [preslavmihaylov/todocheck#9]
*.php uses C Style comments ```// ...```, ```/* ... */``` and comments with ```# ...``` as well. ( See also https://www.php.net/manual/en/language.basic-syntax.comments.php )

```php
// TODO 123: Do something
$obj->doSomething();

/* TODO 123: Do something */
$obj->doSomething();

# TODO 123: Do something
$obj->doSomething();
```

tyvm

**Comment by preslavmihaylov** [comment]
Thanks for the submission. I will let you know of progress
