### ISSUE TITLE
Use regexp for extracting different parts of a URL

### ISSUE THREAD

**Issue by mehdy** [preslavmihaylov/todocheck#91]
Instances

* Inside `IssueAPIOrigin` method in `issuetracker/github/github.go`
* Inside `IssueAPIOrigin` method in `issuetracker/gitlab/gitlab.go`
* Inside `IssueAPIOrigin` method in `issuetracker/pivotaltracker/pivotaltracker.go`

Raised from #81 review.

**Comment by preslavmihaylov** [comment]
Clarification:
 * Use regexp instead of splitting a string into tokens

**Comment by preslavmihaylov** [comment]
After an attempt to implement this #118, I've decided to not go forward with this refactoring as it makes the code less readable than it already is.

The validity of the passed origin is already safeguarded via the validation in [this file](https://github.com/preslavmihaylov/todocheck/blob/788dd095082b6e73514b14d079a9f39dca6f859f/validation/validation.go#L57)
