### ISSUE TITLE
Too much verbosity

### ISSUE THREAD

**Issue by sattellite** [preslavmihaylov/todocheck#95]
If project have many dot-files and ignored paths then each run followed by showing many lines of ignored files `Skipping ignored file...`.  It will be nice to make the todocheck execution was quiet. And add option `-verbose`/`-v` for show all ignored files and may be other lines on future. And use option -v to verbose output instead of version.

**Comment by preslavmihaylov** [comment]
I think using `-v` for version is more aligned with how other tools I've used work. Examples:
 * node
 * npm
 * yarn

But an explicit `--verbose` should do the trick
